### ISSUE TITLE
Add Dark theme Support 

### ISSUE THREAD

**Issue by biomathcode** [amittam104/BentoHub#2]
Current, Dark theme is not supported. 

![Screenshot 2024-07-29 at 09 33 20](https://github.com/user-attachments/assets/38463ed4-a156-4d01-b11e-5b4a04d3a43e)

A lot of people use dark theme

**Comment by amittam104** [comment]
I am not sure where did you got this image. But the last time I updated the app it was supporting dark mode.

![Screenshot 2024-08-03 155212](https://github.com/user-attachments/assets/48036398-0954-49b8-b9e8-b0ed0ae752b9)

**Comment by amittam104** [comment]
Closing the issue
